### ISSUE TITLE
AWS online editor

### ISSUE THREAD

**Issue by uzhas-sovka** [adieuadieu/serverless-chrome#144]
This is not an issue, just a question. How can I edit function directly on AWS? It currently says "function too large, you can't use online editor". Maybe there is a way to show only aws/src/chrome/screenshot.js for example?

**Comment by jaimeiniesta** [comment]
I don't think you can edit part of a function. When it's too large, you need to upload it via a ZIP file or S3 bucket.

**Comment by adieuadieu** [comment]
The AWS Console won't let you edit the code directly in the Lambda console screen because the function artifact (the deployed code package zip) is too large. One way around that is to not include the headless chrome binary in the package and download it from S3 on Lambda invocation. But, serverless-chrome does not currently provide said download-binary-from-S3 feature (see #26). It should also be noted that, loading the binary from S3 on cold-start may incur a greater performance penalty.

**Comment by uzhas-sovka** [comment]
So the only way to debug or and new functionality is to do it locally and deploy afterwards?

**Comment by uzhas-sovka** [comment]
Maybe my question stems from the lack of knowledge of AWS working. I've thought that we have a bunch of (small) js files and Node runtime "executes" them on AWS hardware. And it seems to be wrong. The function is around 40 MB, and it looks like "compiled" (if a may say so, just like illustration) executable and not the pack of sourses.
