### ISSUE TITLE
Getting EACCES error message on lambda

### ISSUE THREAD

**Issue by Huljo** [adieuadieu/serverless-chrome#176]
Hello, 

After redeploying [examples/serverless-framework/aws](https://github.com/adieuadieu/serverless-chrome/tree/master/examples/serverless-framework/aws) and running a GET request on ```/screenshot``` I started seeing this error message on screenshot lambda's logs:

````
UnhandledPromiseRejectionWarning: Error: spawn EACCES
at _errnoException (util.js:1022:11)
at ChildProcess.spawn (internal/child_process.js:323:11)
at exports.spawn (child_process.js:502:9)
at /var/task/src/handlers/screenshot.js:3077:86
at Generator.next (<anonymous>)
at step (/var/task/src/handlers/screenshot.js:2947:193)
at /var/task/src/handlers/screenshot.js:2947:439
at new Promise (<anonymous>)
at /var/task/src/handlers/screenshot.js:2947:101
at Promise (/var/task/src/handlers/screenshot.js:3098:23)
````

Anyone else seeing this?

**Comment by Huljo** [comment]
Hi @SidneyNemzer, 
Yes I deployed from Windows. 
What do you mean by "doesn't support" ? I already deployed lambdas using Serverless from windows without any issue.

**Comment by SidneyNemzer** [comment]
Sorry, I should have linked the issues! Specifically adieuadieu/serverless-chrome#21 and serverless/serverless#3557

The problem is specifically deploying executable files from Windows, because the Windows file system does not preserve the executable permission. My personal work-around is using a Cloud 9 to deploy from, but I imagine that Windows Linux Subsystem (Bash on Ubuntu on WIndows) would work too.

**Comment by Huljo** [comment]
Thank you @SidneyNemzer.
I'll try using docker.

**Comment by zolbayars** [comment]
Hey @Huljo, 
Did it work with docker?
