### ISSUE TITLE
Website does not load properly but does in Chromium

### ISSUE THREAD

**Issue by liambutler-lawrence** [adieuadieu/serverless-chrome#253]
I found this project through following this tutorial:
https://chromedriver.storage.googleapis.com/2.37/chromedriver_mac64.zip

I have been able to get Selenium to successfully create a driver and automate clicking through web pages while on Lambda, which is awesome.

However, this particular web page does not load correctly:
https://www.paclaims.state.pa.us/UCEN/Welcome.asp

Instead of the full HTML, it only loads this:
`<html><head></head><body></body></html>`

Naturally, all my Selenium code following this fails, as there are no elements on the page to manipulate.

I traced down the Chromium version underpinning the version of this that I'm using:

1. Blog post: https://dev.to/mknycha/serverless-web-scraper-in-ruby-tutorial-50hg
2. Recommends version 1.0.0.37: https://github.com/adieuadieu/serverless-chrome/releases/download/v1.0.0-37/stable-headless-chromium-amazonlinux-2017-03.zip
3. Which is from this release: https://github.com/adieuadieu/serverless-chrome/releases/tag/v1.0.0-37
4. Which (looking at the codebase at that tag) is using Chromium version 64.0.3282.167: https://github.com/adieuadieu/serverless-chrome/blob/v1.0.0-37/packages/lambda/builds/chromium/version.json#L4
5. I followed the instructions here to download Chromium at that version: https://www.chromium.org/getting-involved/download-chromium
6. For macOS, that was this: https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Mac%2F520840%2Fchrome-mac.zip?generation=1512101943242165&alt=media

I then pointed my Selenium driver to that Chromium version directly (when running on macOS) and the issue went away (the page loaded fine):

So unless the issue is caused by a difference between the Linux and macOS versions of Chromium, it seems that something in this project must be causing the page not to load.

I'm happy to dig into the issue a little more if somebody can provide a couple pointers, but not sure where to start looking. In other words, I'm not sure what this project adds on to Chromium.

**Comment by gambin** [comment]
I'm having a closer issue here, trying a bunch of different setups of serverless-chromium + chromedriver + seleniumdriver + python versions, but nothing seems to be solved too soon..

What I want to achieve is to use selenium to test an specific system on each 5 minutes. This system has a Angular home login page, after login, user is redirected (302 status code) to another page, that I want to interact and load some controls, but instead of it, the redirect is no working. When I try to run the same code using a "native GUI" chrome, it's working great.

I'll try to continue trying. The possibility to use it on Lambda would be a cost killer solution.

**Comment by gambin** [comment]
Finally I found the 'perfect match':

**requirements.txt**
selenium==3.14.1
chromedriver-binary==2.42

**Makefile**
curl -SL https://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip > chromedriver.zip
curl -SL https://github.com/adieuadieu/serverless-chrome/releases/download/v1.0.0-54/stable-headless-chromium-amazonlinux-2017-03.zip > headless-chromium.zip
