### ISSUE TITLE
Disable popup blocker

### ISSUE THREAD

**Issue by astarr** [adieuadieu/serverless-chrome#27]
More of a question than an issue: I'm trying to use this (excellent!) project to open a web page, do a couple of chores, and get a screenshot. The problem is that one of the chores opens a popup window. And the popup window gets blocked by the popup blocker.

Is there some way to configure the Chrome that gets deployed to allow all popups? There's obviously no need for a popup blocker in this context (is there?). I can't figure out how to do the configuration on the fly.

**Comment by adieuadieu** [comment]
Hi @astarr,

I've not yet encountered the popup issue you've described myself. How do you know that the popup window got blocked? Is there an error message or some indication, or is it an assumption? _(That sounds kind of mean—I don't mean it that way!)_ I'm asking because, my suspicion is that it didn't actually get blocked. Instead, a new tab was created but you wouldn't know it unless you specifically went looking for it.

There are a couple of things you could try:
- Listen for the [Target.targetCreated](https://chromedevtools.github.io/devtools-protocol/tot/Target/#event-targetCreated) event and see if any Target (read: Tab) event is triggered when you open the popup.
- Take a look at all of the Tabs open after the popup with [Target.getTargets](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-getTargets) (or, with a GET to http://127.0.0.1/json)

If none of this helps, ask on the [headless-dev Group (https://groups.google.com/a/chromium.org/forum/#!forum/headless-dev). The Chrome guys there are usually very responsive. If you find a solution, it'd be very appreciated if you come back here to let us know about it!

**Comment by astarr** [comment]
Thanks for your quick response. I'm sure you're right.

I did try both Target.targetCreated and polling CDP.List(), but with no luck on the serverless chrome. It does work fine on a local headless chrome (on Mac OS), though. I've since run into several other problems that make me think I have a more general failure, so please disregard the nonsense about popups!

**Comment by adieuadieu** [comment]
Sure; feel free to reopen if you come full circle back to a popup-blocking issue.
