### ISSUE TITLE
How to deploy and stay under AWS Lambda size limits?

### ISSUE THREAD

**Issue by bluepeter** [adieuadieu/serverless-chrome#28]
Thanks for your work to date on this great project. Everything is working well running locally. However, when I try to deploy, I continually get size issues: `RequestEntityTooLargeException: Request must be smaller than 69905067 bytes for the UpdateFunctionCode operation`

What's the secret to successful deplooyment?

**Comment by adieuadieu** [comment]
Hi @bluepeter,

Yes.. keeping under the size limit is a bit frustrating. serverless@0.16.0 included [this feature](https://github.com/serverless/serverless/pull/3737) which _should_ make it easier to keep `devDependencies` out of the function artefacts when using Serverless. _However_ if you're not using Serverless, and/or are using the `@serverless-chrome/lambda` package directly, you have to take care to not include the `devDependencies` on your own. Also, be sure to deploy by uploading the artefact to S3, rather than directly. This seems to increase the allowed artefact size.

Some things to omit from your bundle:

- chrome-launcher
- lighthouse
- any tooling like babel, or eslint

Currently, `@serverless-chrome/lambda` has a dependency on `chrome-launcher` which itself has a dependency on `lighthouse`. The `chrome-launcher` is used for local-development support. However, it brings the `lighthouse` dependency which is huge. I'll soon push an update which makes `chrome-launcher` an optional dependency—which should make it easier to deploy out of the box. Additionally, I'm going to include #26 in v1.0.

**Comment by bluepeter** [comment]
Thank you for the very detailed response. I also noticed that using S3 is another good option from your other thread here https://github.com/adieuadieu/serverless-chrome/issues/4#issuecomment-308738001 ... did you ever test the true upper bounds of maximum size of a Lambda deployed this way?

**Comment by adieuadieu** [comment]
@bluepeter The direct-upload limit is 66.66MB (technically, just a bit over that.) The limit for the S3 route seems to be the 250MB code/dependency-size limit described [here](http://docs.aws.amazon.com/lambda/latest/dg/limits.html#w135aac55b9c19). I've managed to upload a zip that large, containing 250MB from /dev/urandom. In other words, your zip file can be as large as you want, as long as the total size of it's extracted contents don't exceed 250MB. In practical terms this probably means a zip somewhere around 100MB. Not sure if different regions have different limits. I tested in eu-west-1. The trade-off here is probably that, the larger the S3 package is, the longer the function will take on a cold-start.. not sure about that, though.
