### ISSUE TITLE
Support for Google Cloud Functions

### ISSUE THREAD

**Issue by adieuadieu** [adieuadieu/serverless-chrome#43]
Add support for Google Cloud Functions with package `@serverless-chrome/cloud-functions` and appropriate headless chrome binaries, and include Dockerfile for building Chrome binary. Not super sure about the package name:

`@serverless-chrome/lambda`
`@serverless-chrome/cloud-functions`
`@serverless-chrome/az-functions`

.. a bit inconsistent.

Related: #44 — Support for Azure Functions

**Comment by alex88** [comment]
Someone tried to run chrome on GCF? I've tried to use the binary included with the repo and chrome silently exits with exit code 127, no other stdout/err

**Comment by adieuadieu** [comment]
Hi @alex88 the Lambda binary isn't compiled with the GCF execution environment in mind. However, I have been working on making a GCF-specific build. If nothing unexpected comes up, I should have it working sometime this coming week. :smile:

**Comment by alex88** [comment]
Thank you @adieuadieu, you know the OS/environment GCF runs on?

**Comment by samueller** [comment]
@adieuadieu, eager to know if you were able to get the GCF-specific build working.

**Comment by rosskevin** [comment]
@adieuadieu I'm starting on this and ready to contribute.  Do you have a branch published?

**Comment by PaddyMann** [comment]
Hej, we'd love to use a GCF implementation. Any progress here? What are the current blockers?

**Comment by steren** [comment]
Note that the Node.js **8** runtime for Google Cloud Functions now includes all the necessary OS packages to run Headless Chrome.

Here is a code sample of an HTTP function that returns screenshots:

Main `index.js` file:

    const puppeteer = require('puppeteer');
    
    exports.screenshot = async (req, res) => {
      const url = req.query.url;
    
      if (!url) {
        return res.send('Please provide URL as GET parameter, for example: <a href="?url=https://example.com">?url=https://example.com</a>');
      }
    
      const browser = await puppeteer.launch({
        args: ['--no-sandbox']
      });
      const page = await browser.newPage();
      await page.goto(url);
      const imageBuffer = await page.screenshot();
      browser.close();
    
      res.set('Content-Type', 'image/png');
      res.send(imageBuffer);
    }


and `package.json`

    {
      "name": "screenshot",
      "version": "0.0.1",
      "dependencies": {
        "puppeteer": "^1.2.0"
      }
    }

**Comment by adieuadieu** [comment]
@steren nice! Then there's no need for us to do anything! 🎉

**Comment by gotson** [comment]
what about Java ? I'm using Selenium Java and would like to use GCP instead of AWS.

**Comment by sejka** [comment]
> 
> 
> what about Java ? I'm using Selenium Java and would like to use GCP instead of AWS.

afair gcp functions support only js and python

**Comment by steren** [comment]
The base image has changed between the Node6 and Node8 runtimes.
As I commented, the Node8 runtime has all libraries needed to run headless chrome.

**Comment by ncruces** [comment]
Sorry @steren, this is probably not the most appropriate place to discuss this.

I'm not exactly using this package ([serverless-chrome](https://github.com/adieuadieu/serverless-chrome)), nor [puppeteer](https://github.com/GoogleChrome/puppeteer) mentioned [in this GCP blog](https://cloud.google.com/blog/products/gcp/introducing-headless-chrome-support-in-cloud-functions-and-app-engine).

But I am using something else ([aws-lambda-libreoffice](https://github.com/vladgolubev/aws-lambda-libreoffice)) that depended on much the same libs.

Something changed between 12 and 2pm GMT. `libssl3.so` is now missing from every function I've redeployed since 3pm. This a beta and I really can't complain, but I'd still like to know what happened, can I reach the team somewhere more appropriate?

I'm in the process of testing puppeteer directly to see if it's similarly affected.

**Comment by steren** [comment]
Let's move this discussion to the Cloud Function issue tracker. Please open an issue there and ping it to me.

**Comment by ncruces** [comment]
@steren, thanks: https://issuetracker.google.com/issues/118423830

And sorry adieuadieu for hijacking this issue.

**Comment by adieuadieu** [comment]
Closing this as GCP has built-in package support for Chrome. Nothing for us to do.
