### ISSUE TITLE
Support for Azure Functions

### ISSUE THREAD

**Issue by adieuadieu** [adieuadieu/serverless-chrome#44]
Add support for Azure Functions with package `@serverless-chrome/az-functions` and appropriate headless chrome binaries, and include Dockerfile for building Chrome binary. Not super sure about the package name:

`@serverless-chrome/lambda`
`@serverless-chrome/cloud-functions`
`@serverless-chrome/az-functions`

.. a bit inconsistent.

Related: #43 — Support for Google Cloud Functions

**Comment by sgwatgit** [comment]
At a high level, what are the steps required to get a version of this deployed to Azure Functions?
Are there low-level implementation details that need changed or is it more about the configuration?

I'm really interested in getting some variation of headless Chrome deployed to Azure Functions.

Thanks!

**Comment by Ciantic** [comment]
Have you tested that it works in "regular" Azure either? I had a problems running even the webkitopdf thing because Azure didn't have fonts etc. available. The regular Azure runs under some sandboxed Windows environment.

In the end I had to run Linux App service in Azure, which is a clunky, to generate PDF's.

**Comment by sgwatgit** [comment]
From what I've been looking into recently `wkhtmltopdf` works fine even in Azure Functions' sandboxed environment if the fonts being used are webfonts (like https://fonts.google.com/specimen/Roboto).

You are right - if fonts need to be installed then you're out of luck.

I tested [Puppeteer](https://github.com/GoogleChrome/puppeteer) in Azure Functions and in Azure App Service within the past two weeks and was running into issues when [node was spawning the chrome.exe](https://github.com/GoogleChrome/puppeteer/issues/515) process.

I started to look into the Linux Azure App Service but they are so new that support / documentation isn't really there.

**Comment by Ciantic** [comment]
@sgwatgit there is no documentation, but if you really need the Linux App Services I found out only way to use them is to create template using Visual Studio, it deploys normally to Azure. There is bunch of instructions for Linux App Services and all are outdated, but that is the only thing that worked for me.

I'm running a phantomjs/node thing at the moment in Linux App Service for generating PDF's.

**Comment by hdd42** [comment]
@sgwatgit 

had same problem and tried to use linux as ops (while you create your web app or web app for container select linux instead of windows )
this solved first part of the problem (it took you out of sandbox restrictions) after that select built -in runtime for your app (in my case selected node 8.x)  and deployed it.

at that point  I have to install missing necessary shared library dependencies for chrome.   
[Running Puppeteer in Docker](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md)

just use web ssh and install those deps maually

`apt-get update && apt-get install -yq gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget && rm -r /var/lib/apt/lists/*`

now everything ready to use  Headless Chrome with Puppeteer but one more gotcha in your code need to be done,
chrome has to be launched with no-sanbox flags
 
`let    browser = await puppeteer.launch({
                args: [
                    '--no-sandbox',
                    '--disable-setuid-sandbox'
                ]
            });`

this is the only workaround i could find, hope that helps to someone

**Comment by martingagne** [comment]
Anybody was able to get headless Chrome running in Azure Function or Cloud Services? I am also facing the issue where chrome.exe does not seem to start.

**Comment by jurby** [comment]
+1

**Comment by remote-specialist** [comment]
any progress on this issue? we need it!:)

**Comment by adieuadieu** [comment]
I'm not currently interested in supporting Azure with this project, so I will close this issue.
