### ISSUE TITLE
enhancement: Consider using chrome-launcher for Chrome bootup

### ISSUE THREAD

**Issue by pedro93** [adieuadieu/serverless-chrome#48]
Hello,
 
I just came across your project and noticed you use your own code to verify if chrome is up and running before executing handlers. I came across this npm module a while back https://www.npmjs.com/package/chrome-launcher which is developed by some Google folks which may be interesting for this use case as it can remove your direct need to manage the child process. I have been using it for a while and it seems quite stable.

**Comment by adieuadieu** [comment]
Hi @pedro93 — Thank you for your suggestion.

The launcher code in `@serverless-chrome/lambda` is actually [mostly taken](https://github.com/adieuadieu/serverless-chrome/blob/develop/packages/lambda/src/launcher.js#L2) from `chrome-launcher`. The reason I don't use `chrome-launcher` is because it brings with it too many dependencies. The dependencies add megabytes to the deployment artifact. The biggest offender is the `lighthouse` package which itself brings with it around 15MB, compressed. Since `@serverless-chrome/lambda` with the Chrome binary is already around 47MB, I want to avoid adding anything else that increases the size of the deployment package.

**Comment by pedro93** [comment]
I suspected as much, just FYI the full chrome-launcher dependency size is 1.2MB uncompressed:

```
▶ npm init -y && npm install chrome-launcher --save && du -hs node_modules
Wrote to /home/pedro.cardoso/dev/aux/package.json:

{
  "name": "aux",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN aux@1.0.0 No description
npm WARN aux@1.0.0 No repository field.

+ chrome-launcher@0.3.2
added 21 packages in 6.771s
1,2M	node_modules
```

Thank you for reply and for this project.

**Comment by adieuadieu** [comment]
@pedro93 oh! That's dramatically smaller than last time I tried. Hm.. In that case, it might be worthwhile investigating it again.
