### ISSUE TITLE
How long til a merge into master?

### ISSUE THREAD

**Issue by bluepeter** [adieuadieu/serverless-chrome#51]
Lot of awesome work happening on the develop branch. Are things settling down enough to get a production/master release out the door soon?

**Comment by adieuadieu** [comment]
Hi @bluepeter thank you for your interest. There are still a couple of things I'd like done before merging into master. Mainly, the documentation needs some updating here and there, and the examples need to be fixed/updated. I've been a bit distracted with pushing [Chromeless](https://github.com/graphcool/chromeless) forward but soon will need to swing back here in order to address issues upstream. Anyway, a merge and then a v1.0 will happen—just a matter to time.

**Comment by bluepeter** [comment]
Thanks, that looks like a super interesting project. Hadn't seen that one before. Losing track a bit with all the various repos. It looks like Chromeless effectively is doing the same thing as this project? Or is this project notably different?

(Would be nice to get a framework agnostic headless Chrome so we can use, e.g., Apex, versus Serverless.)

**Comment by adieuadieu** [comment]
@bluepeter Chromeless uses serverless-chrome for it's Proxy/Lambda feature. Chromeless makes working with CDP/DevTools easier/more convenient.

By the way, the `@serverless-chrome/lambda` package in the _develop_ branch (and already [published to npm](https://www.npmjs.com/package/@serverless-chrome/lambda) as a prerelease) is framework agnostic. You should be able to use it with Apex or any other Lambda tools. 😄
