### ISSUE TITLE
Pass HTML string instead of url?

### ISSUE THREAD

**Issue by reinhoceros** [adieuadieu/serverless-chrome#54]
PhantomJs has this neat option of passing a html string instead of a url to render a web page. Is it possible to use serverless-chrome in that way as well?

**Comment by adieuadieu** [comment]
Hi @reinhoceros — This repository isn't really the right place to ask this. serverless-chrome provides the scaffolding to get headless Chrome deployed and launched within a Serverless context (AWS Lambda). What you do with Chrome once it's launched is up to you.

You can use the [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface) project to drive the interaction with headless Chrome using the Chrome DevTools Protocol which is documented [here](https://chromedevtools.github.io/devtools-protocol/tot/). Specifically, you might be looking for [Page.setDocumentContent()](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-setDocumentContent). Of course, using the Chrome DevTools Protocol to do simple tasks is quite cumbersome, which is why projects like [Chromeless](https://github.com/graphcool/chromeless) exist to make it easier to get things done. In Chromeless, you might be interested in the [setHtml()](https://github.com/graphcool/chromeless/blob/master/docs/api.md#api-sethtml) method.
